import UIKit

public protocol HomeNavigationAdapter {
    func navigateToLocationSearch(from viewController: UIViewController?, purpose: HomePurpose)
    func navigateToLocationForProjects(from viewController: UIViewController?)
    func navigateToDubaiTransaction(from viewController: UIViewController?)
    func navigateToLocationAndAgentPicker(from viewController: UIViewController?, purpose: HomePurpose)
    func navigateToFindAgents(from viewController: UIViewController?)
    func navigateToBlogs(url: String, title: String?, from viewController: UIViewController?)
    func navigateToLocationForTransactions(from viewController: UIViewController?, purpose: HomePurpose)
    func naviagteToAllBlogs(from viewController: UIViewController?)
    func navigateToNearbySearch(location: LocationHit, from viewController: UIViewController?)
    func navigateToSavedSearch(savedSearchData: [String: Any], resolvedLocations: [LocationHit], from viewController: UIViewController?)
    func navigateToAllFavorites(from viewController: UIViewController?)
    func navigateToAllSavedSearches(from viewController: UIViewController?)
    func navigateToPropertyDetail(with externalId: String, from viewController: UIViewController?)
    func navigateToProjectDetail(hit: ProjectHit, jsonDict: [String: Any], from viewController: UIViewController?)
    func navigateToProjectsScreen(externalID: String, displayName: String, from viewController: UIViewController?)
    func navigateToRecentSearch(recentSearch: HomeScreenRecentSearch, from viewController: UIViewController?)
    func navigateToCommuteSearch(from viewController: UIViewController?)
    func navigateToTruEstimate(from viewController: UIViewController?)
    func navigateToGPT(from viewController: UIViewController?)
    func navigateToSellerLeadsForm(with purpose: HomePurpose?, from viewController: UIViewController?)
    func navigateToPopularSearch(category: PopularSearchCategory, purpose: PopularSearchPurpose, from viewController: UIViewController?)
    func navigateToFavoriteAction(action: FavouriteCellAction, from viewController: UIViewController?)
    func navigateToOnboarding(from viewController: UIViewController?)
    func navigateToOnboardingV2(from viewController: UIViewController?)
    func navigateToAppReviewFlow(from viewController: UIViewController?)
}
