//
//  HomeSectionBuilder.swift
//  Home
//
//  Created by Hammad Shahid on 01/04/2026.
//

import Foundation

final class HomeSectionBuilder {
    
    func buildSections(sectionsData: Home.HomeSections) -> [AnySection] {
        var sections: [AnySection] = []
        
        
        // Append TruBroker Banner
        let truBrokerBannerSection = TruBrokerBannerSection()
        sections.append(AnySection(truBrokerBannerSection, isCustomizable: false))
        
        // Append SellerLeads Banner
        let sellerLeadsBannerSection = SellerLeadsBannerSection()
        sections.append(AnySection(sellerLeadsBannerSection, isCustomizable: false))

        // MARK: - Build Railing Carousel
        let railingCellTypes: [RailingCellType] = [
            .truEstimate,
            .bayutGPT,
            .dubaiTransactions,
            .commuteSearch
        ]
        
        let railingActions = RailingActions(delegate: sectionsData.viewController)
        let railingGroup = RailingGroup(cellTypes: railingCellTypes, actions: railingActions)
        sections.append(contentsOf: railingGroup.buildSections())
        
        // MARK: - Build New Projects Group
        let newProjectsActions = NewProjectsActions(delegate: sectionsData.viewController)
        let newProjectsGroup = NewProjectsGroup(
            headerTitle: "New Projects",
            viewAllTitle: "View all projects",
            projects: sectionsData.projects,
            locations: sectionsData.locations,
            actions: newProjectsActions
        )
        
        // Append all modular fragments generated by the group
        sections.append(contentsOf: newProjectsGroup.buildSections())
        
        let favouritesActions = FavouritesActions(delegate: sectionsData.viewController)
        let favouritesGroup = FavouritesGroup(
            title: "Favourites",
            viewAllTitle: "View all favourites",
            properties: sectionsData.favourites,
            actions: favouritesActions
        )
        sections.append(contentsOf: favouritesGroup.buildSections())
        
        let savedSearchesActions = SavedSearchesActions(delegate: sectionsData.viewController)
        let savedSearchesGroup = SavedSearchesGroup(
            title: "Saved Searches",
            viewAllTitle: "View all saved searches",
            searches: sectionsData.savedSearches,
            actions: savedSearchesActions
        )
        sections.append(contentsOf: savedSearchesGroup.buildSections())
        
        let nearbyActions = NearbyLocationsActions(delegate: sectionsData.viewController)
        let nearbyGroup = NearbyLocationsGroup(
            title: "Nearby Locations",
            isLocationEnabled: sectionsData.isLocationEnabled,
            locations: sectionsData.nearbyLocations,
            actions: nearbyActions
        )
        sections.append(contentsOf: nearbyGroup.buildSections())
        
        let popularSearchActions = PopularSearchActions(delegate: sectionsData.viewController)
        let popularSearchGroup = PopularSearchGroup(
            title: "Popular Searches",
            purposes: sectionsData.purposes,
            selectedPurpose: sectionsData.selectedPurpose,
            searches: sectionsData.popularSearches,
            actions: popularSearchActions
        )
        sections.append(contentsOf: popularSearchGroup.buildSections())
        
        let blogsActions = BlogsActions(delegate: sectionsData.viewController)
        let blogsGroup = BlogsGroup(
            title: "From our Blog",
            viewAllTitle: "View all blogs",
            blogs: sectionsData.blogs,
            actions: blogsActions
        )
        sections.append(contentsOf: blogsGroup.buildSections())
        
        return sections
    }
}
