//
//  HomeSectionBuilder.swift
//  Home
//
//  Created by Hammad Shahid on 01/04/2026.
//

import Foundation

final class HomeSectionBuilder {
    
    func buildSections(sectionsData: Home.HomeSections) -> [AnySection] {
        var sections: [AnySection] = []
        
        // Recent Searches
        let recentSearchesActions = RecentSearchesActions(delegate: sectionsData.viewController)
        let recentSearchesGroup = RecentSearchesGroup(
            title: "str_recent_searches".localized(),
            searches: sectionsData.recentSearches,
            actions: recentSearchesActions
        )
        sections.append(contentsOf: recentSearchesGroup.buildSections())
        
        // Append TruBroker Banner
        if sectionsData.showTruBrokerBanner {
            let truBrokerActions = TruBrokerBannerActions(delegate: sectionsData.viewController)
            let truBrokerBannerSection = TruBrokerBannerSection(actions: truBrokerActions)
            sections.append(AnySection(truBrokerBannerSection, isCustomizable: false))
        }
        
        // Append SellerLeads Banner
        if sectionsData.showSellerLeadsBanner {
            let sellerLeadsActions = SellerLeadsBannerActions(delegate: sectionsData.viewController)
            let sellerLeadsBannerSection = SellerLeadsBannerSection(actions: sellerLeadsActions)
            sections.append(AnySection(sellerLeadsBannerSection, isCustomizable: false))
        }

        // MARK: - Build Railing Carousel
        let railingCellTypes: [RailingCellType] = [
            .truEstimate,
            .bayutGPT,
            .dubaiTransactions,
            .commuteSearch
        ]
        
        let railingActions = RailingActions(delegate: sectionsData.viewController)
        let railingGroup = RailingGroup(cellTypes: railingCellTypes, actions: railingActions)
        sections.append(contentsOf: railingGroup.buildSections())
        
        // MARK: - Stories Section
        if let storiesProvider = HomeModule.shared.storiesProvider,
           storiesProvider.hasContent,
           let storiesView = storiesProvider.getStoriesWidgetView() {
            let storiesSection = StoriesSection(hostedView: storiesView, viewHeight: HomeModule.shared.environment.storiesViewHeight)
            sections.append(AnySection(storiesSection, isCustomizable: false))
        }
        
        let savedSearchesActions = SavedSearchesActions(delegate: sectionsData.viewController)
        let savedSearchGroup = SavedSearchesGroup(
            title: "savedSearches".localized(),
            viewAllTitle: "viewAllSavedSearches".localized(),
            searches: sectionsData.savedSearches,
            actions: savedSearchesActions
        )
        sections.append(contentsOf: savedSearchGroup.buildSections())
        
        // MARK: - Build New Projects Group
        let newProjectsActions = NewProjectsActions(delegate: sectionsData.viewController)
        let newProjectsGroup = NewProjectsGroup(
            headerTitle: "browseNewProjectsInUAE".localized(),
            viewAllTitle: .empty,
            projects: sectionsData.projects,
            locations: sectionsData.locations,
            actions: newProjectsActions
        )
        
        // Append all modular fragments generated by the group
        sections.append(contentsOf: newProjectsGroup.buildSections())
        
        let favouritesActions = FavouritesActions(delegate: sectionsData.viewController)
        let favouritesGroup = FavouritesGroup(
            title: "favourites".localized(),
            viewAllTitle: "viewAllFavourites".localized(),
            properties: sectionsData.favourites,
            actions: favouritesActions
        )
        sections.append(contentsOf: favouritesGroup.buildSections())
        
        let popularSearchActions = PopularSearchActions(delegate: sectionsData.viewController)
        let popularSearchGroup = PopularSearchGroup(
            title: String(format: "popularIn".localized(), sectionsData.popularSearchDisplayedLocation ?? sectionsData.selectedLocation),
            purposes: sectionsData.purposes,
            selectedPurpose: sectionsData.selectedPurpose,
            searches: sectionsData.popularSearches,
            actions: popularSearchActions
        )
        sections.append(contentsOf: popularSearchGroup.buildSections())
        
        let nearbyActions = NearbyLocationsActions(delegate: sectionsData.viewController)
        let nearbyGroup = NearbyLocationsGroup(
            title: "lookupNearbyLocations".localized(),
            isLocationEnabled: sectionsData.isLocationEnabled,
            locations: sectionsData.nearbyLocations,
            actions: nearbyActions
        )
        sections.append(contentsOf: nearbyGroup.buildSections())
        
        
        let blogsActions = BlogsActions(delegate: sectionsData.viewController)
        let blogsGroup = BlogsGroup(
            title: "fromOurBlogs".localized(),
            viewAllTitle: "exploreArticles".localized(),
            blogs: sectionsData.blogs,
            actions: blogsActions
        )
        sections.append(contentsOf: blogsGroup.buildSections())
        
        // MARK: - Marketing Banner Dynamic Injection
        if let config = sectionsData.marketingBannerConfig, config.isEnabled {
            let bannerSection = MarketingBannerSection(imageUrl: config.bannerImageUrl)
            let anySection = AnySection(bannerSection, isCustomizable: false)
            
            let insertionIndex = min(max(0, config.index), sections.count)
            sections.insert(anySection, at: insertionIndex)
        }
        
        return sections
    }
}
