//
//  HomeSectionBuilder.swift
//  Home
//
//  Created by Hammad Shahid on 01/04/2026.
//

import Foundation

final class HomeSectionBuilder {
    
    func buildSections(sectionsData: Home.HomeSections) -> [AnySection] {
        var sections: [AnySection] = []
        
        
        // Append TruBroker Banner
        let truBrokerBannerSection = TruBrokerBannerSection()
        sections.append(AnySection(truBrokerBannerSection, isCustomizable: false))
        
        // Append SellerLeads Banner
        let sellerLeadsBannerSection = SellerLeadsBannerSection()
        sections.append(AnySection(sellerLeadsBannerSection, isCustomizable: false))

        // MARK: - Build Railing Carousel
        let railingCellTypes: [RailingCellType] = [
            .truEstimate,
            .bayutGPT,
            .dubaiTransactions,
            .commuteSearch
        ]
        
        let railingActions = RailingActions(delegate: sectionsData.viewController)
        let railingGroup = RailingGroup(cellTypes: railingCellTypes, actions: railingActions)
        sections.append(contentsOf: railingGroup.buildSections())
        
        // MARK: - Build New Projects Group
        let newProjectsActions = NewProjectsActions(delegate: sectionsData.viewController)
        let newProjectsGroup = NewProjectsGroup(
            headerTitle: "New Projects",
            viewAllTitle: "View all projects",
            projects: sectionsData.projects,
            locations: sectionsData.locations,
            actions: newProjectsActions
        )
        
        // Append all modular fragments generated by the group
        sections.append(contentsOf: newProjectsGroup.buildSections())
        
        let favouritesActions = FavouritesActions(delegate: sectionsData.viewController)
        let favouritesGroup = FavouritesGroup(
            title: "Favourites",
            viewAllTitle: "View all favourites",
            properties: sectionsData.favourites,
            actions: favouritesActions
        )
        sections.append(contentsOf: favouritesGroup.buildSections())
        
        let savedSearchesActions = SavedSearchesActions(delegate: sectionsData.viewController)
        let savedSearchesGroup = SavedSearchesGroup(
            title: "Saved Searches",
            viewAllTitle: "View all saved searches",
            searches: sectionsData.savedSearches,
            actions: savedSearchesActions
        )
        sections.append(contentsOf: savedSearchesGroup.buildSections())
        
        return sections
    }
}
