//
//  HomeSectionBuilder.swift
//  Home
//
//  Created by Hammad Shahid on 01/04/2026.
//

import Foundation

final class HomeSectionBuilder {
    
    func buildSections(sectionsData: Home.HomeSections) -> [AnySection] {
        var sections: [AnySection] = []
        // MARK: - Build New Projects Group
        let newProjectsActions = NewProjectsActions(delegate: sectionsData.viewController)
        let newProjectsGroup = NewProjectsGroup(
            headerTitle: "New Projects",
            viewAllTitle: "View all projects",
            projects: sectionsData.projects,
            locations: sectionsData.locations,
            actions: newProjectsActions
        )
        
        // Append all modular fragments generated by the group
        sections.append(contentsOf: newProjectsGroup.buildSections())
        
        return sections
    }
}
